project_name: Survival
audio_directory: /Users/jonevans/Documents/Unreal Projects/Survival/Survival_WwiseProject/Originals/SFX/
ue4_project_path: /Users/jonevans/Documents/Unreal Projects/Survival/Survival_WwiseProject/Survival_WwiseProject.wproj
wwise_project_path: /Users/jonevans/Documents/Unreal Projects/Survival/Survival_WwiseProject/Originals/SFX/
